# Generated by Django 4.2.3 on 2024-02-15 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools_orders', '0001_initial'),
        ('schools_bookings', '0001_initial'),
        ('users', '0011_rename_notes_user_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoenrollment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools_orders.order'),
        ),
        migrations.AddField(
            model_name='scoenrollment',
            name='swimling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.swimling'),
        ),
        migrations.AddField(
            model_name='scoenrollment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools_bookings.scoterm'),
        ),
        migrations.AddIndex(
            model_name='scoenrollment',
            index=models.Index(fields=['term', 'lesson', 'swimling'], name='schools_boo_term_id_1fe463_idx'),
        ),
    ]
