# Generated by Django 4.2.3 on 2024-02-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools_bookings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoterm',
            old_name='booking_date',
            new_name='booking_end_date',
        ),
        migrations.RenameField(
            model_name='scoterm',
            old_name='rebooking_date',
            new_name='booking_start_date',
        ),
    ]
