# Generated by Django 4.2.3 on 2024-02-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_scocategory_program'),
        ('schools_bookings', '0003_rename_booking_date_scoterm_booking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoterm',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms', to='schools.scoschool'),
        ),
        migrations.AlterField(
            model_name='scoterm',
            name='assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
