# Generated by Django 4.2.3 on 2024-02-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_scolessons_area_scolessons_school'),
        ('schools_bookings', '0004_scoterm_school_alter_scoterm_assessment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoterm',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_terms', to='schools.scoschool'),
        ),
    ]
