# Generated by Django 5.2.2 on 2025-07-13 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0005_alter_product_end_time_alter_product_start_time'),
        ('lessons_bookings', '0007_alter_lessonenrollment_unique_together'),
        ('users', '0014_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('swimling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.swimling')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons_bookings.term')),
            ],
            options={
                'unique_together': {('swimling', 'term')},
            },
        ),
        migrations.CreateModel(
            name='LessonSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.product')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.skill')),
            ],
            options={
                'ordering': ['lesson', 'order'],
                'unique_together': {('lesson', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')])),
                ('notes', models.TextField(blank=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.skill')),
                ('swimling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.swimling')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons_bookings.term')),
            ],
            options={
                'unique_together': {('swimling', 'skill', 'term')},
            },
        ),
    ]
