# Generated by Django 5.2.2 on 2025-07-13 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreAquaticSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lessonskill',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='skill',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='cas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='progress.coreaquaticskill'),
            preserve_default=False,
        ),
    ]
