# Generated by Django 5.2.2 on 2025-07-21 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_product_end_time_alter_product_start_time'),
        ('progress', '0002_coreaquaticskill_alter_lessonskill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreaquaticskill',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coreaquaticskill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CategorySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.category')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.skill')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('category', 'skill')},
            },
        ),
        migrations.DeleteModel(
            name='LessonSkill',
        ),
    ]
