# Generated by Django 5.2.2 on 2025-07-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_coreaquaticskill_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreaquaticskill',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
