# Generated by Django 5.2.2 on 2025-08-07 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_category_short_name'),
        ('lessons_bookings', '0008_alter_lessonenrollment_swimling'),
        ('progress', '0003_coreaquaticskill_abbreviation_and_more'),
        ('users', '0014_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillassessment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='skillassessment',
            name='notes',
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.product'),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐☆☆☆☆'), (2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆'), (5, '⭐⭐⭐⭐⭐')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='skillassessment',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='skillassessment',
            index=models.Index(fields=['swimling', 'term'], name='progress_sk_swimlin_673bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='skillassessment',
            index=models.Index(fields=['term', 'skill'], name='progress_sk_term_id_73ba05_idx'),
        ),
    ]
