# Generated by Django 5.2.2 on 2025-08-11 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_remove_skillassessment_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillassessment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
