# Generated by Django 5.2.2 on 2025-08-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_alter_skillassessment_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryskill',
            options={'ordering': ['category__stage', 'order']},
        ),
    ]
