# Generated by Django 4.2.3 on 2023-08-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_swimling_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swimling',
            old_name='school_role_number',
            new_name='sco_role_num',
        ),
    ]
