# Generated by Django 4.2.3 on 2023-08-03 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swimling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(null=True)),
                ('school_role_number', models.CharField(blank=True, max_length=6, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('wp_student_id', models.IntegerField(null=True)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_swimlings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
