# Generated by Django 4.2.3 on 2023-09-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notes_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
