# Generated by Django 4.2.3 on 2024-01-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_notes_userprofile_notes_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimling',
            name='first_name',
            field=models.CharField(default='AN', max_length=255),
            preserve_default=False,
        ),
    ]
