# Generated by Django 4.2.3 on 2023-08-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_swimling_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimling',
            name='wp_student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
