# Generated by Django 4.2.3 on 2024-02-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_swimling_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='notes_extra',
            new_name='notes',
        ),
    ]
