# Generated by Django 4.2.3 on 2024-02-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_notes_extra_userprofile_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='notes',
            new_name='admin_notes',
        ),
    ]
