# Generated by Django 4.2.3 on 2024-05-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_notes_user_admin_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimling',
            name='sco_role_num',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
