# Generated by Django 5.2.2 on 2025-07-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_swimling_sco_role_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
