# Generated by Django 5.2.2 on 2026-03-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimling',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
