# Generated by Django 5.2.2 on 2026-08-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_swimling_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimling',
            name='medical_info',
            field=models.TextField(blank=True, help_text='Anything a teacher needs to know at poolside, e.g. asthma, epilepsy, allergies, or a hearing aid.', null=True, verbose_name='Medical information'),
        ),
    ]
