# ************************************************************
# Sequel Ace SQL dump
# Version 20095
#
# https://sequel-ace.com/
# https://github.com/Sequel-Ace/Sequel-Ace
#
# Host: localhost (MySQL 9.3.0)
# Database: lcaim
# Generation Time: 2025-10-18 11:33:04 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
SET NAMES utf8mb4;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE='NO_AUTO_VALUE_ON_ZERO', SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table interactive_lessons_question
# ------------------------------------------------------------

DROP TABLE IF EXISTS `interactive_lessons_question`;

CREATE TABLE `interactive_lessons_question` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `text` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `answer` longtext COLLATE utf8mb4_unicode_ci,
  `hint` longtext COLLATE utf8mb4_unicode_ci,
  `topic_id` bigint NOT NULL,
  `order` int unsigned NOT NULL,
  `section` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `solution` longtext COLLATE utf8mb4_unicode_ci,
  `image_url` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `solution_image` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `interactive_lessons__topic_id_7b237e26_fk_interacti` (`topic_id`),
  CONSTRAINT `interactive_lessons__topic_id_7b237e26_fk_interacti` FOREIGN KEY (`topic_id`) REFERENCES `interactive_lessons_topic` (`id`),
  CONSTRAINT `interactive_lessons_question_chk_1` CHECK ((`order` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

LOCK TABLES `interactive_lessons_question` WRITE;
/*!40000 ALTER TABLE `interactive_lessons_question` DISABLE KEYS */;

INSERT INTO `interactive_lessons_question` (`id`, `text`, `answer`, `hint`, `topic_id`, `order`, `section`, `solution`, `image_url`, `image`, `solution_image`)
VALUES
	(1,'What is the mean of the following numbers: 3,4,5','','The average',1,0,'Definitions','4',NULL,'',NULL),
	(2,'**Question 1**  \nFrom the following set of numbers, calculate the **mean** and the **mode**:  \n\n$3, 12, 17, 24, 24, 31, 34, 39$','Mean 23\nMode 24','**Hint:**  \n\nTo work out the **mean**, use the formula:\n\n$$\n\\text{Mean} = \\dfrac{\\text{Sum of all numbers}}{\\text{Number of numbers}}\n$$\n\nIn simpler terms, add up all the numbers and divide by how many there are.\n\nTo find the **mode**, identify the number that appears most often in the set.',1,1,'Mean','**Question 1**  \n\nFrom the following set of numbers, calculate the **mean** and the **mode**:  \n\n$3,\\ 12,\\ 17,\\ 24,\\ 24,\\ 31,\\ 34,\\ 39$\n\n**Solution:**  \n\nTo find the mean:\n\n$$\n\\text{Mean} = \\dfrac{3 + 12 + 17 + 24 + 24 + 31 + 34 + 39}{8} = 23\n$$\n\nThe **mode** is the number that appears most often - **24**.',NULL,'',NULL),
	(3,'From the following set of numbers, calculate the **mean** & the **mode**:\n\n$6, 9, 12, 15, 15, 18, 19, 20, 23, 27, 27, 27, 30, 32$','Mean: 20\nMode: 27','Same as the average',1,2,'Mean Median, Mode','',NULL,'',NULL),
	(4,'The mean number of points scored by a Gaelic football team per game in a 12-game\nseason is /(21./) If the number of points scored in 11 of the games is:\n\n7, 8, 11, 15, 20, 21, 24, 26, 29, 35, 40\n\nfind the number of points scored in the **12th game**','16','',1,3,'Mean Mode Median','We can rearrange the formula from Questions 1 and 2 to get:\n\n$$\n\\text{Sum} = \\text{Mean} \\times \\text{Number of Numbers}\n$$\n\nWe know what our mean is, and we have 12 games, so there will be 12 numbers.\n\nThis means that:\n\n$$\n\\text{Sum} = 21 \\times 12 = 252\n$$\n\nWhen we add up all the points scored by the team throughout the season we should get 252.\n\nWe can add the numbers we have together and add \\(x\\) for the value that we are trying to find.  \nWe know that they should equal 252, so with this equation we can solve for \\(x\\),  \nthe number of points scored in the 12\\textsuperscript{th} game.\n\n$$\n7 + 8 + 11 + 15 + 20 + 21 + 24 + 26 + 29 + 35 + 40 + x = 236 + x\n$$\n\nThis means that:\n\n$$\n236 + x = 252\n$$\n\nTo solve for \\(x\\), we can subtract 236 from both sides to give us:\n\n$$\nx = 16\n$$',NULL,'',NULL),
	(5,'Find the mean and mode of the following data set:\n\n5, 6, 7, 9, 10, 10, 12, 14, 15','Mean: 9.78 (rounded to 2 decimal places)\nMode: 10','',1,4,'Mean Mode','Add all the numbers:\n\n$$\n5 + 6 + 7 + 9 + 10 + 10 + 12 + 14 + 15 = 88\n$$\n\nThere are 9 numbers, so:\n\n$$\n\\text{Mean} = \\frac{88}{9} \\approx 9.78\n$$\n\nThe mode is \\(10\\) because it appears more than once.',NULL,'',NULL),
	(6,'Find the **mean** and **mode** of the following numbers:\n\n18, 21, 23, 23, 25, 26, 28, 30, 32, 35','Mean: 26.1\nMode: 23','',1,5,'Mean Mode','Add all the numbers:\n\n$$\n18 + 21 + 23 + 23 + 25 + 26 + 28 + 30 + 32 + 35 = 261\n$$\n\nThere are 10 numbers, so:\n\n$$\n\\text{Mean} = \\frac{261}{10} = 26.1\n$$\n\nThe mode is \\(23\\) because it appears twice, more than any other number.',NULL,'',NULL),
	(7,'The mean score in a class test of 15 students was 68.  \nThe scores of 14 students were:  \n45, 52, 55, 61, 64, 65, 70, 71, 74, 77, 80, 84, 86, 90.  \nFind the score of the 15\\textsuperscript{th} student.','18','We use the formula:\n\n$$\n\\text{Total Sum} = \\text{Mean} \\times \\text{Number of Scores}\n$$\n\nSo the total of all 15 students\' scores is:\n\n$$\n68 \\times 15 = 1020\n$$\n\nAdd the scores of the 14 known students:\n\n$$\n45 + 52 + 55 + 61 + 64 + 65 + 70 + 71 + 74 + 77 + 80 + 84 + 86 + 90 = 938\n$$\n\nNow subtract from the total to find the missing student\'s score:\n\n$$\n1020 - 938 = 82\n$$\n\nSo, the 15\\textsuperscript{th} student scored \\(82\\).',1,6,'Mea Mode','We use the formula:\n\n$$\n\\text{Total Sum} = \\text{Mean} \\times \\text{Number of Scores}\n$$\n\nSo the total of all 15 students\' scores is:\n\n$$\n68 \\times 15 = 1020\n$$\n\nAdd the scores of the 14 known students:\n\n$$\n45 + 52 + 55 + 61 + 64 + 65 + 70 + 71 + 74 + 77 + 80 + 84 + 86 + 90 = 938\n$$\n\nNow subtract from the total to find the missing student\'s score:\n\n$$\n1020 - 938 = 82\n$$\n\nSo, the 15\\textsuperscript{th} student scored \\(82\\).',NULL,'',NULL),
	(8,'**Question 1**\n\nThe test results of students who recently sat a maths exam are shown below.  \nFrom the table, estimate the mean score of students who took the exam.\n\n| Score Range | No. of People |\n|--------------|---------------|\n| 0%-20%       | 3             |\n| 20%-40%      | 6             |\n| 40%-60%      | 12            |\n| 60%-80%      | 14            |\n| 80%-100%     | 5             |','','',1,7,'grouped-data questions','Find the mid-interval values of all the intervals.  \nFor example, the mid-interval value of 20%-40% is 30%.  \n\nMultiply each mid-interval value by the frequency with which it occurs,  \nadd these products together, and divide by the total number of students.\n\n$$\n\\text{Mean} = \\frac{(10)(3) + (30)(6) + (50)(12) + (70)(14) + (90)(5)}{3 + 6 + 12 + 14 + 5}\n$$\n\n$$\n\\text{Mean} = \\frac{1680}{40} = 56\\\\%\n$$\n\nSo the estimated mean score of students who took the exam is **56%**.',NULL,'',NULL),
	(9,'From the same table, in which interval does the median lie?\n\n| Score Range | No. of People |\n|--------------|---------------|\n| 0%-20%       | 3             |\n| 20%-40%      | 6             |\n| 40%-60%      | 12            |\n| 60%-80%      | 14            |\n| 80%-100%     | 5             |','40%-60%','',1,8,'grouped-data questions','There are 40 students in total, so the median will be the 20\\textsuperscript{th}-21\\textsuperscript{st} values.\n\nCumulative frequencies:\n\n| Interval | Cumulative Frequency |\n|-----------|----------------------|\n| 0%-20%    | 3                    |\n| 20%-40%   | 9                    |\n| 40%-60%   | 21                   |\n| 60%-80%   | 35                   |\n| 80%-100%  | 40                   |\n\nThe 20\\textsuperscript{th} and 21\\textsuperscript{st} observations lie in the **40%-60% interval**.  \n\nTherefore, the **median interval is 40%-60%**.',NULL,'',NULL),
	(10,'The flight delay time, in minutes, for a particular airline is shown below.  \nUsing mid-interval values from the table, estimate the mean flight delay time.  \nIn which interval does the median lie?\n\n| Delay Time (minutes) | No. of Flights |\n|-----------------------|----------------|\n| 0-10                 | 24             |\n| 10-20                | 18             |\n| 20-30                | 11             |\n| 30-40                | 13             |\n| 40-50                | 9              |\n| 50-60                | 5              |','Find the mid-interval values and multiply each by its frequency.\n\n$$\n\\text{Mean} = \\frac{(5)(24) + (15)(18) + (25)(11) + (35)(13) + (45)(9) + (55)(5)}{24 + 18 + 11 + 13 + 9 + 5}\n$$\n\n$$\n\\text{Mean} = \\frac{1800}{80} = 22.5 \\text{ minutes}\n$$\n\nSo the estimated mean flight delay time is **22.5 minutes**.\n\nTo find the median interval, calculate cumulative frequencies:\n\n| Interval | Cumulative Frequency |\n|-----------|----------------------|\n| 0-10      | 24                   |\n| 10-20     | 42                   |\n| 20-30     | 53                   |\n| 30-40     | 66                   |\n| 40-50     | 75                   |\n| 50-60     | 80                   |\n\nThe total number of flights is 80, so the median is the 40\\textsuperscript{th}-41\\textsuperscript{st} values.  \nThese lie in the **10-20 interval**.\n\nTherefore, the **median interval is 10-20 minutes**.','',1,9,'grouped-data questions','Find the mid-interval values and multiply each by its frequency.\n\n$$\n\\text{Mean} = \\frac{(5)(24) + (15)(18) + (25)(11) + (35)(13) + (45)(9) + (55)(5)}{24 + 18 + 11 + 13 + 9 + 5}\n$$\n\n$$\n\\text{Mean} = \\frac{1800}{80} = 22.5 \\text{ minutes}\n$$\n\nSo the estimated mean flight delay time is **22.5 minutes**.\n\nTo find the median interval, calculate cumulative frequencies:\n\n| Interval | Cumulative Frequency |\n|-----------|----------------------|\n| 0-10      | 24                   |\n| 10-20     | 42                   |\n| 20-30     | 53                   |\n| 30-40     | 66                   |\n| 40-50     | 75                   |\n| 50-60     | 80                   |\n\nThe total number of flights is 80, so the median is the 40\\textsuperscript{th}-41\\textsuperscript{st} values.  \nThese lie in the **10-20 interval**.\n\nTherefore, the **median interval is 10-20 minutes**.',NULL,'',NULL),
	(11,'Find the range of:  \n8, 16, 3, 18, 7, 14, 6','','',1,10,'Range & Interquartile Range','First, arrange the numbers in ascending order:\n\n$$\n3, 6, 7, 8, 14, 16, 18\n$$\n\nThe range is found by subtracting the smallest value from the largest value:\n\n$$\n\\text{Range} = 18 - 3 = 15\n$$\n\nSo, the range is **15**.',NULL,'',NULL),
	(12,'Find the interquartile range of:  \n8, 16, 3, 18, 7, 14, 6','10','',1,11,'Range & Interquartile Range','Arrange the numbers in ascending order:\n\n$$\n3, 6, 7, 8, 14, 16, 18\n$$\n\nThere are \\(n = 7\\) values.\n\nTo find the quartile positions:\n\n$$\nQ_1 = \\frac{1}{4}(n + 1) = \\frac{1}{4}(8) = 2\n$$\n\n$$\nQ_3 = \\frac{3}{4}(n + 1) = \\frac{3}{4}(8) = 6\n$$\n\nThe 2nd value is \\(6\\), and the 6th value is \\(16\\).\n\nTherefore:\n\n$$\n\\text{IQR} = Q_3 - Q_1 = 16 - 6 = 10\n$$\n\nSo, the interquartile range is **10**.',NULL,'',NULL),
	(13,'Find the range and interquartile range of:  \n9, 20, 28, 6, 1, 11, 24, 4, 26, 19','','',1,12,'Range & Interquartile Range','Arrange the numbers in ascending order:\n\n$$\n1, 4, 6, 9, 11, 19, 20, 24, 26, 28\n$$\n\n**Range:**\n\n$$\n\\text{Range} = 28 - 1 = 27\n$$\n\nThere are \\(n = 10\\) values.\n\nTo find the quartile positions:\n\n$$\nQ_1 = \\frac{1}{4}(n + 1) = \\frac{1}{4}(11) = 2.75\n$$\n\n$$\nQ_3 = \\frac{3}{4}(n + 1) = \\frac{3}{4}(11) = 8.25\n$$\n\nFor \\(Q_1 = 2.75\\), take the 2nd and 3rd terms (4 and 6):\n\n$$\nQ_1 = \\frac{4 + 6}{2} = 5\n$$\n\nFor \\(Q_3 = 8.25\\), take the 8th and 9th terms (24 and 26):\n\n$$\nQ_3 = \\frac{24 + 26}{2} = 25\n$$\n\nThen:\n\n$$\n\\text{IQR} = Q_3 - Q_1 = 25 - 5 = 20\n$$\n\nSo,  \n**Range = 27**  \n**Interquartile Range = 20**',NULL,'',NULL),
	(14,'Find the standard deviation of the set:  \n{10, 14, 16, 21, 23}  \nGive your answer correct to 3 decimal places.','4.707','',1,13,'Standard Deviation','To find the standard deviation, we use the formula:\n\n$$\n\\sigma = \\sqrt{\\frac{1}{n} \\sum (x - \\mu)^2}\n$$\n\nwhere each \\(x\\) is a value in the set, \\(\\mu\\) is the mean, and \\(n\\) is the number of values.\n\nFirst, find the mean:\n\n$$\n\\mu = \\frac{10 + 14 + 16 + 21 + 23}{5} = \\frac{84}{5} = 16.8\n$$\n\nNow find each \\((x - \\mu)^2\\):\n\n| \\(x\\) | \\(x - \\mu\\) | \\((x - \\mu)^2\\) |\n|-------|--------------|----------------|\n| 10 | -6.8 | 46.24 |\n| 14 | -2.8 | 7.84 |\n| 16 | -0.8 | 0.64 |\n| 21 | 4.2 | 17.64 |\n| 23 | 6.2 | 38.44 |\n\nAdd them up:\n\n$$\n\\sum (x - \\mu)^2 = 46.24 + 7.84 + 0.64 + 17.64 + 38.44 = 110.8\n$$\n\nThen divide by \\(n = 5\\) and take the square root:\n\n$$\n\\sigma = \\sqrt{\\frac{110.8}{5}} = \\sqrt{22.16} = 4.707\n$$\n\nSo, the standard deviation is **4.707** (to 3 decimal places).\n\n---',NULL,'',NULL),
	(15,'Find the standard deviation of the set:  \n{8, 12, 19, 27, 33, 34, 36, 36}  \nGive your answer correct to 1 decimal place.','10.5','',1,14,'Standard Deviation','Formula:\n\n$$\n\\sigma = \\sqrt{\\frac{1}{n} \\sum (x - \\mu)^2}\n$$\n\nFirst, find the mean:\n\n$$\n\\mu = \\frac{8 + 12 + 19 + 27 + 33 + 34 + 36 + 36}{8} = \\frac{205}{8} = 25.625\n$$\n\nNow calculate each \\((x - \\mu)^2\\) and sum:\n\n$$\n\\sum (x - \\mu)^2 = 882.75\n$$\n\nThen:\n\n$$\n\\sigma = \\sqrt{\\frac{882.75}{8}} = \\sqrt{110.34} = 10.5\n$$\n\nSo, the standard deviation is **10.5** (to 1 decimal place).',NULL,'',NULL),
	(16,'Find the standard deviation of the numbers:  \n{6, 8, 11, 14, 15, 16, 18, 24, 25, 25, 26, 28, 38, 40}  \nGive your answer correct to 1 decimal place.','9.9','',1,15,'Standard Deviation','Formula:\n\n$$\n\\sigma = \\sqrt{\\frac{1}{n} \\sum (x - \\mu)^2}\n$$\n\nFirst, find the mean:\n\n$$\n\\mu = \\frac{6 + 8 + 11 + 14 + 15 + 16 + 18 + 24 + 25 + 25 + 26 + 28 + 38 + 40}{14} = \\frac{294}{14} = 21\n$$\n\nNow compute:\n\n$$\n\\sum (x - \\mu)^2 = 1378\n$$\n\nThen:\n\n$$\n\\sigma = \\sqrt{\\frac{1378}{14}} = \\sqrt{98.43} = 9.9\n$$\n\nSo, the standard deviation is **9.9** (to 1 decimal place).',NULL,'',NULL),
	(17,'Using a calculator, calculate the standard deviation of the set:  \n\\(A = \\{9, 13, 14, 15, 19\\}\\)','**3.22**.','',1,16,'Standard Deviation using Calculator','Input the numbers from set \\(A\\) into your calculator using the statistics function.\n\nThe calculator gives:\n\n$$\n\\sigma_A = 3.22\n$$\n\nSo, the standard deviation is **3.22**.',NULL,'',NULL),
	(18,'Using your calculator, calculate the standard deviation of the set:  \n\\(B = \\{2, 5, 6, 7, 3, 8, 11\\}\\)','Enter the data values into your calculator\'s statistics mode.  \n\nThe calculator gives:\n\n$$\n\\sigma_B = 2.83\n$$\n\nSo, the standard deviation is **2.83**.','',1,17,'Standard Deviation using a calculator','',NULL,'',NULL),
	(19,'Using a calculator, calculate the standard deviation of the set:  \n\\(C = \\{3.2, 4.6, 2.8, 5.2, 4.4\\}\\)','0.898','',1,18,'Standard Deviation using a Calculator','Input the data into your calculator using the standard deviation function.  \n\nThe calculator gives:\n\n$$\n\\sigma_C = 0.898\n$$\n\nSo, the standard deviation is **0.898**.',NULL,'',NULL),
	(20,'The ages of 20 random people in a shopping centre at a given time were recorded.  \nThe ranked results are as follows:  \n\n17, 16, 20, 28, 29, 24, 30, 32, 32, 32, 36, 38, 39, 43, 47, 51, 57, 57, 58, 72  \n\n\\(a\\) Display these results in a stem and leaf plot.  \n\\(b\\) Calculate the range of the ages.','\\(a\\)\n1,67\n2,0489\n3,0222689\n4,37\n5,1778\n7,2\n\\(b\\)\n56','',1,19,'Stem and Leaf Plot','\\(a\\) **Stem and Leaf Plot**\n\n| Stem | Leaf |\n|:----:|:----:|\n| 1 | 6 7 |\n| 2 | 0 4 8 9 |\n| 3 | 0 2 2 2 6 8 9 |\n| 4 | 3 7 |\n| 5 | 1 7 7 8 |\n| 7 | 2 |\n\n**Key:** 3 | 6 means 36 years old.\n\n---\n\n\\(b\\) **Range**\n\nThe range is found by subtracting the smallest value from the largest value:\n\n$$\n\\text{Range} = 72 - 16 = 56\n$$\n\nSo, the range of the ages is **56 years**.',NULL,'',NULL),
	(21,'The time (in seconds) taken for a group of 3rd years and a group of 6th years to complete a 100m sprint are as follows:\n\n- **3rd Years:** 13.8, 14.2, 14.4, 14.6, 14.7, 14.9, 15.0, 15.1, 15.6, 15.8, 17.5, 17.9  \n- **6th Years:** 13.2, 13.6, 13.9, 14.5, 14.5, 14.7, 15.8, 15.8, 16.2, 16.3, 17.0, 17.1  \n\nDisplay this information on a back-to-back stem and leaf plot.','**Back-to-Back Stem and Leaf Plot**\n\n| 6th Years | Stem | 3rd Years |\n|:----------:|:----:|:----------:|\n| 2 | 13 | 8 |\n| 6 3 | 14 | 2 4 6 7 9 |\n| 8 8 | 15 | 0 1 6 8 |\n| 2 3 | 16 |  |\n| 0 1 | 17 | 5 9 |\n\n**Keys:**  \n6 | 13 = 13.6 (6th Year)  \n13 | 8 = 13.8 (3rd Year)','',1,20,'Stem and Leaf Plots','**Back-to-Back Stem and Leaf Plot**\n\n| 6th Years | Stem | 3rd Years |\n|:----------:|:----:|:----------:|\n| 2 | 13 | 8 |\n| 6 3 | 14 | 2 4 6 7 9 |\n| 8 8 | 15 | 0 1 6 8 |\n| 2 3 | 16 |  |\n| 0 1 | 17 | 5 9 |\n\n**Keys:**  \n6 | 13 = 13.6 (6th Year)  \n13 | 8 = 13.8 (3rd Year)',NULL,'',NULL),
	(22,'Calculate the interquartile range for the 3rd years\' time and the 6th years\' time in Question 2 above.\n\n- **3rd Years:** 13.8, 14.2, 14.4, 14.6, 14.7, 14.9, 15.0, 15.1, 15.6, 15.8, 17.5, 17.9  \n- **6th Years:** 13.2, 13.6, 13.9, 14.5, 14.5, 14.7, 15.8, 15.8, 16.2, 16.3, 17.0, 17.1','1.2\n2.05','',1,21,'Interquartile Ramge','**3rd Years\' Data (ordered):**\n\n13.8, 14.2, 14.4, 14.6, 14.7, 14.9, 15.0, 15.1, 15.6, 15.8, 17.5, 17.9\n\nThere are \\(n = 12\\) values.\n\nThe median (middle of the data) is between the 6th and 7th values:\n\n$$\n\\text{Median} = \\frac{14.9 + 15.0}{2} = 14.95\n$$\n\nLower quartile \\(Q_1\\) is the median of the lower half:\n\n$$\nQ_1 = \\frac{14.4 + 14.6}{2} = 14.5\n$$\n\nUpper quartile \\(Q_3\\) is the median of the upper half:\n\n$$\nQ_3 = \\frac{15.6 + 15.8}{2} = 15.7\n$$\n\nHence, the interquartile range (IQR) is:\n\n$$\n\\text{IQR} = Q_3 - Q_1 = 15.7 - 14.5 = 1.2\n$$\n\n**3rd Year IQR = 1.2**\n\n---\n\n**6th Years\' Data (ordered):**\n\n13.2, 13.6, 13.9, 14.5, 14.5, 14.7, 15.8, 15.8, 16.2, 16.3, 17.0, 17.1\n\nMedian (middle of the data):\n\n$$\n\\text{Median} = \\frac{14.7 + 15.8}{2} = 15.25\n$$\n\nLower quartile \\(Q_1\\):\n\n$$\nQ_1 = \\frac{13.9 + 14.5}{2} = 14.2\n$$\n\nUpper quartile \\(Q_3\\):\n\n$$\nQ_3 = \\frac{16.2 + 16.3}{2} = 16.25\n$$\n\nHence:\n\n$$\n\\text{IQR} = Q_3 - Q_1 = 16.25 - 14.2 = 2.05\n$$\n\n**6th Year IQR = 2.05**',NULL,'',''),
	(23,'The histogram below shows the daily screen time in hours of a sample of students.  \nCopy and complete the following table. Give your answers correct to two decimal places where necessary.','','',1,22,'Histograms and distributions','From the histogram we read the frequencies and fill the table.\n\n| Interval (hrs) | Frequency | Percentage |\n|:---------------:|:----------:|:-----------:|\n| 0-10 | 3 | 4.62 % |\n| 10-20 | 7 | 10.77 % |\n| 20-30 | 12 | 18.46 % |\n| 30-40 | 20 | 30.77 % |\n| 40-50 | 14 | 21.54 % |\n| 50-60 | 9 | 13.85 % |\n| **Total** | **65** | **100 %** |\n\nPercentages are found using:\n\n$$\n\\text{Percentage} = \n\\frac{\\text{Frequency}}{\\text{Total}} \\times 100\n$$',NULL,'question_images/studenttv_QdGS1bj.png',NULL),
	(24,'🧮 **Question**  \nConstruct a histogram to display the following data:\n\n| Interval (hrs) | Frequency |\n|:--------------:|:----------:|\n| 0-10  | 3  |\n| 10-20 | 7  |\n| 20-30 | 12 |\n| 30-40 | 20 |\n| 40-50 | 14 |\n| 50-60 | 9  |','','',1,23,'Histogram','✅ **Solution**\n\nSince all the class intervals have equal width of \\(10\\) hours,  \nthe frequency of each class can be used directly as the height of each bar in the histogram.\n\n| Interval (hrs) | Frequency | Class Width | Frequency Density |\n|:--------------:|:----------:|:-------------:|:-----------------:|\n| 0-10  | 3  | 10 | \\(\\frac{3}{10} = 0.3\\) |\n| 10-20 | 7  | 10 | \\(\\frac{7}{10} = 0.7\\) |\n| 20-30 | 12 | 10 | \\(\\frac{12}{10} = 1.2\\) |\n| 30-40 | 20 | 10 | \\(\\frac{20}{10} = 2.0\\) |\n| 40-50 | 14 | 10 | \\(\\frac{14}{10} = 1.4\\) |\n| 50-60 | 9  | 10 | \\(\\frac{9}{10} = 0.9\\) |\n\nThe histogram is drawn with:\n- The horizontal axis labeled **\"Interval (hrs)\"** from \\(0\\) to \\(60\\),\n- The vertical axis labeled **\"Frequency Density\"**,  \n- Bars of equal width \\(10\\) and heights corresponding to the densities above.',NULL,'',''),
	(25,'🧮 **Question**  \nIf a data set is normally distributed, which of the following is true:\n\nA. \\(\\text{mean} = \\text{median} = \\text{mode}\\)  \nB. \\(\\text{mean} < \\text{median} < \\text{mode}\\)  \nC. \\(\\text{mean} > \\text{median} > \\text{mode}\\)','','',1,24,'Normal Distributions','✅ **Solution**  \nFor a **normal distribution**, the curve is perfectly symmetrical about the mean.  \nHence, all three measures of central tendency are equal.\n\n\\[\n\\text{mean} = \\text{median} = \\text{mode}\n\\]\n\n✅ **Correct answer:** A',NULL,'',''),
	(26,'🧮 **Question**  \nDescribe the shape of the distribution shown below:','','',1,25,NULL,'✅ **Solution**  \nThe histogram shows that most of the data are concentrated on the **left** side,  \nand the tail extends to the **right**.\n\nTherefore, the distribution is **positively skewed** (or **skewed to the right**).\n\nIn this case:\n\\[\n\\text{mean} > \\text{median} > \\text{mode}\n\\]',NULL,'question_images/Screen_Shot_2025-10-12_at_08.46.01_a.m..png',''),
	(27,'**Question**\nConsider the distribution below. Labelled at A, B and C are estimated values of the distribution\'s central tendencies: mean, median and mode.  \nMatch each letter to its corresponding central tendency.\n\n![Question Image](question_image.jpg)','','',1,26,'Histograms','**Solution**\nThe distribution is **positively skewed** (tail to the right).  \nFor a positively skewed distribution:\n\n$$ \\text{mode} < \\text{median} < \\text{mean} $$\n\nFrom the diagram (left to right):\n- \\(A\\) is the **mode** (highest bar, leftmost)\n- \\(B\\) is the **median**\n- \\(C\\) is the **mean**\n\n\\[\n\\boxed{A = \\text{mode}, \\quad B = \\text{median}, \\quad C = \\text{mean}}\n\\]',NULL,'question_images/Screen_Shot_2025-10-12_at_08.50.36_a.m..png',''),
	(28,'**Question**\nExplain what is meant by a **scatterplot** and **correlation**.  \nDescribe the different types of correlation that can occur between two variables.','','',1,27,'Scatterplots and Correlation','**Solution**\nA **scatterplot** is a graph showing the relationship between two variables.  \nEach point on the plot represents one pair of values \\((x, y)\\).\n\n**Correlation** measures the strength and direction of the relationship between two variables.\n\nTypes of correlation:\n- **Positive correlation**: As one variable increases, the other also increases.  \n  (Points rise from left to right.)\n- **Negative correlation**: As one variable increases, the other decreases.  \n  (Points fall from left to right.)\n- **Zero (no) correlation**: There is no apparent relationship between the variables.  \n  (Points are scattered randomly.)\n\nThe **correlation coefficient**, denoted by \\(r\\), measures how strong the relationship is:\n\\[\n-1 \\le r \\le 1\n\\]\n- \\(r = 1\\): perfect positive correlation  \n- \\(r = -1\\): perfect negative correlation  \n- \\(r = 0\\): no correlation',NULL,'',''),
	(29,'**Question**\nConstruct a scatterplot to display the data in the table below.  \nHence, describe the correlation between the rainfall and the number of customers.\n\n| Rainfall (mm) | Customers |\n|:--------------:|:----------:|\n| 0 | 80 |\n| 2 | 78 |\n| 4 | 75 |\n| 6 | 70 |\n| 8 | 65 |\n| 10 | 60 |\n| 12 | 55 |','','',1,28,'Scatterplots and Correlation','**Solution**\nPlot the points \\((0, 80)\\), \\((2, 78)\\), \\((4, 75)\\), \\((6, 70)\\), \\((8, 65)\\), \\((10, 60)\\), \\((12, 55)\\) on a scatterplot  \nwith **Rainfall (mm)** on the x-axis and **Customers** on the y-axis.\n\nAs rainfall increases, the number of customers decreases.  \nThis shows a **strong negative correlation** between rainfall and number of customers.',NULL,'','solutions/Screen_Shot_2025-10-12_at_08.57.07_a.m..png'),
	(30,'**Question**\nConstruct a scatterplot to display the data in the table below.  \n\n| Temperature (°C) | Ice Cream Sales |\n|:----------------:|:----------------:|\n| 14 | 40 |\n| 16 | 45 |\n| 18 | 55 |\n| 20 | 65 |\n| 22 | 75 |\n| 24 | 85 |\n| 26 | 95 |','','',1,29,NULL,'**Solution**\nPlot the points \\((14, 40)\\), \\((16, 45)\\), \\((18, 55)\\), \\((20, 65)\\), \\((22, 75)\\), \\((24, 85)\\), \\((26, 95)\\)  \non a scatterplot with **Temperature (°C)** on the x-axis and **Ice Cream Sales** on the y-axis.\n\nAs temperature increases, ice cream sales also increase.  \nThis shows a **strong positive correlation** between temperature and ice cream sales.',NULL,'','solutions/Screen_Shot_2025-10-12_at_09.03.14_a.m..png'),
	(31,'**Question**\nThe scatterplot below shows the results of students who took a maths and a physics exam.  \nComplete the table below stating the results of each student in their maths and physics exams.','','',1,30,'Scatterplots and Correlation','**Solution**\nFrom the scatterplot, the approximate coordinates (Maths, Physics) for each student are:\n\n| Maths | Physics |\n|:------:|:--------:|\n| 40 | 55 |\n| 50 | 95 |\n| 60 | 90 |\n| 75 | 85 |\n| 75 | 80 |\n| 80 | 80 |\n| 90 | 85 |\n| 100 | 95 |\n\nThese points represent each student\'s marks in Maths (x-axis) and Physics (y-axis).',NULL,'','solutions/Screen_Shot_2025-10-12_at_09.07.09_a.m..png'),
	(32,'**Question**\nThe number of hours spent studying for a particular test and the students\' test result is displayed on the scatterplot below.  \nDescribe the correlation between the number of hours spent studying and the test result.','','',1,31,'Correlation from Scatterplots','**Solution**\nFrom the scatterplot, as the number of hours spent studying increases, the students\' test results also increase.  \nThe points form an upward trend, showing a **strong positive correlation** between hours studied and test result.\n\nThis means that students who study for longer tend to achieve higher marks.',NULL,'question_images/Screen_Shot_2025-10-12_at_09.12.28_a.m..png',''),
	(33,'**Question**\nA test was conducted to see if there is a relationship between a person\'s height and the number of push-ups they can do.  \nThe results are displayed in the scatterplot below.  \nDescribe the correlation between the two variables.','','',1,32,'Scatterplots and Correlation','**Solution**\nFrom the scatterplot, as the number of push-ups increases, the height of the person tends to decrease slightly.  \nThis shows a **weak negative correlation** between height and number of push-ups.\n\nIn general, shorter individuals in this sample tend to complete more push-ups, but the relationship is not strong.',NULL,'question_images/Screen_Shot_2025-10-12_at_09.17.28_a.m..png',''),
	(34,'**Question**\nA Credit Union studied the relationship between a number of its members\' weekly savings versus the number of take-aways they buy per week.  \nThe results are displayed in the scatterplot below.  \nDescribe the correlation between the two variables.','','',1,33,'Correlation from Scatterplots','**Solution**\nFrom the scatterplot, as the number of take-aways per week increases, the amount of weekly savings decreases.  \nThis shows a **strong negative correlation** between the number of take-aways and weekly savings.\n\nIn other words, members who buy more take-aways tend to save less money each week.',NULL,'question_images/Screen_Shot_2025-10-12_at_09.19.51_a.m..png',''),
	(35,'**Question**\nThe data below states the number of years\' work experience a worker has versus their salary.  \nCalculate, correct to two decimal places, the correlation coefficient of this data.  \nHence, describe the strength of the correlation.\n\n| Experience (years) | Salary (€1000s) |\n|:------------------:|:----------------:|\n| 1 | 25 |\n| 2 | 28 |\n| 3 | 35 |\n| 4 | 40 |\n| 5 | 45 |\n| 6 | 50 |\n| 7 | 55 |','1','',1,34,'Calculating Correlation Coefficient (r)','**Solution**\nLet \\(x\\) represent **Experience (years)** and \\(y\\) represent **Salary (€1000s)**.\n\n| x | y | x - \\bar{x} | y - \\bar{y} | (x - \\bar{x})(y - \\bar{y}) | (x - \\bar{x})^2 | (y - \\bar{y})^2 |\n|:-:|:-:|:-:|:-:|:-:|:-:|:-:|\n| 1 | 25 | -3 | -15 | 45 | 9 | 225 |\n| 2 | 28 | -2 | -12 | 24 | 4 | 144 |\n| 3 | 35 | -1 | -5 | 5 | 1 | 25 |\n| 4 | 40 | 0 | 0 | 0 | 0 | 0 |\n| 5 | 45 | 1 | 5 | 5 | 1 | 25 |\n| 6 | 50 | 2 | 10 | 20 | 4 | 100 |\n| 7 | 55 | 3 | 15 | 45 | 9 | 225 |\n\n\\[\n\\sum (x - \\bar{x})(y - \\bar{y}) = 144, \\quad\n\\sum (x - \\bar{x})^2 = 28, \\quad\n\\sum (y - \\bar{y})^2 = 744\n\\]\n\n\\[\nr = \\frac{\\sum (x - \\bar{x})(y - \\bar{y})}\n{\\sqrt{\\sum (x - \\bar{x})^2 \\sum (y - \\bar{y})^2}}\n= \\frac{144}{\\sqrt{28 \\times 744}}\n\\]\n\n\\[\nr = \\frac{144}{\\sqrt{20832}} = \\frac{144}{144.3} \\approx 1.00\n\\]\n\n\\[\n\\boxed{r = 1.00}\n\\]\n\n**Interpretation:**  \nThere is a **perfect positive correlation** between experience and salary - as experience increases, salary increases proportionally.',NULL,'',''),
	(36,'**Question**\nThe data below represents a student\'s grade point average (GPA) and their screen time in hours on a particular weekend day.  \nCalculate the correlation coefficient of the data, correct to two decimal places.\n\n| GPA | Screen Time (hrs) |\n|:---:|:-----------------:|\n| 3.8 | 2.0 |\n| 3.6 | 2.5 |\n| 3.5 | 3.0 |\n| 3.2 | 3.5 |\n| 3.0 | 4.0 |\n| 2.8 | 4.5 |\n| 2.6 | 5.0 |\n| 2.4 | 5.5 |','-0.99','',1,35,'Calculating Correlation Coefficient (r)','**Solution**\nLet \\(x\\) = GPA, \\(y\\) = Screen Time (hrs).\n\n\\[\n\\bar{x} = \\frac{3.8 + 3.6 + 3.5 + 3.2 + 3.0 + 2.8 + 2.6 + 2.4}{8} = 3.1125\n\\]\n\\[\n\\bar{y} = \\frac{2.0 + 2.5 + 3.0 + 3.5 + 4.0 + 4.5 + 5.0 + 5.5}{8} = 3.75\n\\]\n\nWe calculate deviations:\n\n| x | y | x−\\bar{x} | y−\\bar{y} | (x−\\bar{x})(y−\\bar{y}) | (x−\\bar{x})² | (y−\\bar{y})² |\n|:-:|:-:|:-:|:-:|:-:|:-:|:-:|\n| 3.8 | 2.0 | 0.6875 | -1.75 | -1.2031 | 0.4727 | 3.0625 |\n| 3.6 | 2.5 | 0.4875 | -1.25 | -0.6094 | 0.2376 | 1.5625 |\n| 3.5 | 3.0 | 0.3875 | -0.75 | -0.2906 | 0.1502 | 0.5625 |\n| 3.2 | 3.5 | 0.0875 | -0.25 | -0.0219 | 0.0077 | 0.0625 |\n| 3.0 | 4.0 | -0.1125 | 0.25 | -0.0281 | 0.0127 | 0.0625 |\n| 2.8 | 4.5 | -0.3125 | 0.75 | -0.2344 | 0.0977 | 0.5625 |\n| 2.6 | 5.0 | -0.5125 | 1.25 | -0.6406 | 0.2627 | 1.5625 |\n| 2.4 | 5.5 | -0.7125 | 1.75 | -1.2469 | 0.5077 | 3.0625 |\n\n\\[\n\\sum (x−\\bar{x})(y−\\bar{y}) = -4.28, \\quad \n\\sum (x−\\bar{x})^2 = 1.75, \\quad \n\\sum (y−\\bar{y})^2 = 10.5\n\\]\n\n\\[\nr = \\frac{\\sum (x−\\bar{x})(y−\\bar{y})}{\\sqrt{\\sum (x−\\bar{x})^2 \\sum (y−\\bar{y})^2}}\n= \\frac{-4.28}{\\sqrt{1.75 \\times 10.5}}\n= \\frac{-4.28}{\\sqrt{18.375}}\n= \\frac{-4.28}{4.29} \\approx -0.99\n\\]\n\n\\[\n\\boxed{r = -0.99}\n\\]\n\n**Interpretation:**  \nThere is a **very strong negative correlation** between GPA and screen time - students with higher screen time tend to have lower GPAs.',NULL,'',''),
	(37,'**Question**\nA student wishes to determine whether a relationship between their class\'s results in maths and physics exists.  \nThey select the grades of eight random students.  \nCalculate, correct to two decimal places, the correlation coefficient of the data.  \nHence, describe the relationship between the data.\n\n| Maths | Physics |\n|:-----:|:-------:|\n| 65 | 60 |\n| 70 | 68 |\n| 75 | 70 |\n| 80 | 75 |\n| 85 | 78 |\n| 90 | 85 |\n| 95 | 88 |\n| 100 | 92 |','0.99','',1,36,'Calculating Correlation Coefficient (r)','**Solution**\nLet \\(x\\) = Maths, \\(y\\) = Physics.\n\n\\[\n\\bar{x} = \\frac{65 + 70 + 75 + 80 + 85 + 90 + 95 + 100}{8} = 82.5\n\\]\n\\[\n\\bar{y} = \\frac{60 + 68 + 70 + 75 + 78 + 85 + 88 + 92}{8} = 77\n\\]\n\n| x | y | x−\\bar{x} | y−\\bar{y} | (x−\\bar{x})(y−\\bar{y}) | (x−\\bar{x})² | (y−\\bar{y})² |\n|:-:|:-:|:-:|:-:|:-:|:-:|:-:|\n| 65 | 60 | -17.5 | -17 | 297.5 | 306.25 | 289 |\n| 70 | 68 | -12.5 | -9 | 112.5 | 156.25 | 81 |\n| 75 | 70 | -7.5 | -7 | 52.5 | 56.25 | 49 |\n| 80 | 75 | -2.5 | -2 | 5 | 6.25 | 4 |\n| 85 | 78 | 2.5 | 1 | 2.5 | 6.25 | 1 |\n| 90 | 85 | 7.5 | 8 | 60 | 56.25 | 64 |\n| 95 | 88 | 12.5 | 11 | 137.5 | 156.25 | 121 |\n| 100 | 92 | 17.5 | 15 | 262.5 | 306.25 | 225 |\n\n\\[\n\\sum (x−\\bar{x})(y−\\bar{y}) = 930, \\quad\n\\sum (x−\\bar{x})^2 = 1049, \\quad\n\\sum (y−\\bar{y})^2 = 834\n\\]\n\n\\[\nr = \\frac{\\sum (x−\\bar{x})(y−\\bar{y})}\n{\\sqrt{\\sum (x−\\bar{x})^2 \\sum (y−\\bar{y})^2}}\n= \\frac{930}{\\sqrt{1049 \\times 834}}\n\\]\n\n\\[\nr = \\frac{930}{\\sqrt{874,866}} = \\frac{930}{935.9} \\approx 0.99\n\\]\n\n\\[\n\\boxed{r = 0.99}\n\\]\n\n**Interpretation:**  \nThere is a **very strong positive correlation** between Maths and Physics results.  \nStudents who score highly in Maths also tend to score highly in Physics.',NULL,'',''),
	(38,'**Question**\nFor the mean of the sample \\(\\bar{x}\\) to approximately equal the population mean \\(\\mu\\), the sample size must be greater than or equal to what value?','30','',2,1,'Sampling Distributions','**Solution**\nAccording to the Central Limit Theorem, the sampling distribution of the mean \\(\\bar{x}\\) is approximately normal if the sample size \\(n\\) is sufficiently large.\n\nIn practice, this occurs when:\n\n$$\nn \\ge 30\n$$\n\nTherefore, the sample size must be **at least 30** for \\(\\bar{x}\\) to approximately equal \\(\\mu\\).',NULL,'',''),
	(39,'Question\n**Question**\nWhat is the formula for the standard deviation of the sampling distribution?','','',2,2,'Sampling Distributions','✅ Solution\n\nThe standard deviation of the sampling distribution (also called the **standard error**) is given by\n\n$$\n\\sigma_{\\bar{x}} = \\frac{\\sigma}{\\sqrt{n}} \\, .\n$$\n\n**Where:**\n- $ \\sigma_{\\bar{x}} $ - standard deviation of the sampling distribution (standard error)\n- $ \\sigma $ - population standard deviation\n- $ n $ - sample size',NULL,'',''),
	(40,'**Question**\r\nIf $p = 2$, $q = -3$ and $r = 5$, evaluate:','','',3,1,'Substitution','**Solution**\r\nGiven $p = 2$, $q = -3$, $r = 5$:\r\n\r\n\\(i\\) $2pq = 2(2)(-3) = -12$\r\n\r\n(ii) $(q + r)p = (-3 + 5)(2) = 2(2) = 4$\r\n\r\n(iii) $\\dfrac{q + p}{2r} = \\dfrac{-3 + 2}{2(5)} = \\dfrac{-1}{10}$\r\n\r\n(iv) $pr - q^2 = (2)(5) - (-3)^2 = 10 - 9 = 1$\r\n\r\n\\(v\\) $\\sqrt{\\dfrac{q^2 + rp + 4}{p}} \r\n= \\sqrt{\\dfrac{(-3)^2 + (5)(2) + 4}{2}} \r\n= \\sqrt{\\dfrac{9 + 10 + 4}{2}} \r\n= \\sqrt{\\dfrac{23}{2}}$',NULL,'',''),
	(41,'**Question**\nSimplify each expression:\n\n\\(i\\) $2x - 3y + 4x - 2y + 3x + y$  \n(ii) $5a - 2b + 3a - (b - 4a)$','','',3,2,'Simplify','**Solution**\n\\(i\\) Combine like terms:\n$$\n2x + 4x + 3x = 9x, \\quad -3y - 2y + y = -4y\n$$\nSo, $9x - 4y$.\n\n(ii) Expand the brackets:\n$$\n5a - 2b + 3a - (b - 4a) = 5a - 2b + 3a - b + 4a\n$$\nCombine like terms:\n$$\n(5a + 3a + 4a) - (2b + b) = 12a - 3b\n$$\nFinal answer: $12a - 3b$.',NULL,'',''),
	(42,'**Question**\r\nSolve for $x$:\r\n$$\r\n10x^2 + 6x - 52 = 0\r\n$$','2,  -13/5','',3,3,'Formulae','**Solution**\r\nGiven the quadratic equation $10x^2 + 6x - 52 = 0$.\r\n\r\nUsing the quadratic formula\r\n$$\r\nx = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a},\r\n$$\r\nwhere $a = 10$, $b = 6$, $c = -52$.\r\n\r\nSubstitute:\r\n$$\r\nx = \\frac{-6 \\pm \\sqrt{6^2 - 4(10)(-52)}}{2(10)}.\r\n$$\r\n\r\nSimplify:\r\n$$\r\nx = \\frac{-6 \\pm \\sqrt{36 + 2080}}{20}\r\n= \\frac{-6 \\pm \\sqrt{2116}}{20}.\r\n$$\r\n\r\nSince $\\sqrt{2116} = 46$,\r\n$$\r\nx = \\frac{-6 \\pm 46}{20}.\r\n$$\r\n\r\nHence,\r\n$$\r\nx = \\frac{40}{20} = 2\r\n\\quad \\text{or} \\quad\r\nx = \\frac{-52}{20} = -\\frac{13}{5}.\r\n$$\r\n\r\nFinal answer: $x = 2$ or $x = -\\dfrac{13}{5}$.',NULL,'',''),
	(43,'**Question**\r\nA rectangle has sides $x + 2$ and $x + 4$.\r\n\r\n(a) Find its perimeter.  \r\n(b) Find its area as a polynomial.','x^2 + 6x + 8','',3,4,NULL,'**Solution**\r\n(a) Perimeter:\r\n$$\r\nP = 2[(x + 2) + (x + 4)] = 2(2x + 6) = 4x + 12\r\n$$\r\n\r\n(b) Area:\r\n$$\r\nA = (x + 2)(x + 4) = x^2 + 6x + 8\r\n$$',NULL,'',''),
	(44,'**Question**\r\nSolve $x^2 + 64 = 0$.','','',4,1,'Basic Complex Numbers','**Solution**\r\nBring the $64$ to the other side:\r\n$$\r\nx^2 = -64\r\n$$\r\n\r\nTo solve for $x$, take the square root of both sides:\r\n$$\r\nx = \\pm \\sqrt{-64}\r\n$$\r\n\r\nWe know that $\\sqrt{-1} = i$, so\r\n$$\r\n\\sqrt{-64} = \\sqrt{64} \\times \\sqrt{-1} = 8i\r\n$$\r\n\r\nTherefore,\r\n$$\r\nx = \\pm 8i\r\n$$',NULL,'',''),
	(45,'**Question**\r\nSimplify $i^{32}$.','','',4,2,'Basic Complex Numbers','**Solution**\r\nWe know that:\r\n$$\r\ni^1 = i,\\quad i^2 = -1,\\quad i^3 = -i,\\quad i^4 = 1\r\n$$\r\n\r\nThe powers of $i$ repeat every $4$ terms.\r\n\r\nSo, to simplify $i^{32}$, divide the exponent by $4$:\r\n$$\r\n32 \\div 4 = 8 \\text{ remainder } 0\r\n$$\r\n\r\nSince the remainder is $0$, we have:\r\n$$\r\ni^{32} = (i^4)^8 = 1^8 = 1\r\n$$\r\n\r\nTherefore,\r\n$$\r\ni^{32} = 1\r\n$$',NULL,'',''),
	(46,'**Question**\r\nSimplify $i^{21}$.','','',4,3,'Basic Complex Numbers','**Solution**\r\nWe know the powers of $i$ repeat every $4$ terms:\r\n$$\r\ni^1 = i,\\quad i^2 = -1,\\quad i^3 = -i,\\quad i^4 = 1\r\n$$\r\n\r\nTo simplify $i^{21}$, divide the exponent by $4$:\r\n$$\r\n21 \\div 4 = 5 \\text{ remainder } 1\r\n$$\r\n\r\nSince the remainder is $1$, we have:\r\n$$\r\ni^{21} = i^1 = i\r\n$$\r\n\r\nTherefore,\r\n$$\r\ni^{21} = i\r\n$$',NULL,'',''),
	(47,'**Question**\r\nIf $ z_1 = 3 + 6i $ and $ z_2 = 4 + 3i $. Evaluate $ z_1 + z_2 $.','','',4,4,'Adding and Subtracting Complex Numbers','**Solution**\r\nTo add complex numbers, add their real parts and their imaginary parts separately.\r\n\r\n$$\r\nz_1 + z_2 = (3 + 6i) + (4 + 3i)\r\n$$\r\n\r\nCombine like terms:\r\n$$\r\n= (3 + 4) + (6i + 3i)\r\n$$\r\n\r\nSimplify:\r\n$$\r\nz_1 + z_2 = 7 + 9i\r\n$$',NULL,'',''),
	(48,'**Question**\r\nIf $ z_1 = 5 + 4i $ and $ z_2 = 6 - 2i $. Evaluate $ z_1 - z_2 $.','','',4,5,'Adding and Subtracting Complex Numbers','**Solution**\r\nTo subtract complex numbers, subtract their real parts and their imaginary parts separately.\r\n\r\n$$\r\nz_1 - z_2 = (5 + 4i) - (6 - 2i)\r\n$$\r\n\r\nSimplify:\r\n$$\r\n= (5 - 6) + (4i - (-2i))\r\n$$\r\n\r\n$$\r\n= -1 + 6i\r\n$$\r\n\r\nTherefore,\r\n$$\r\nz_1 - z_2 = -1 + 6i\r\n$$',NULL,'',''),
	(49,'**Question**\r\nIf $ z_1 = -3 + 4i $ and $ z_2 = 6 - 2i $, evaluate $ 3z_1 - 2z_2 $.','','',4,6,'Adding and Subtracting Complex Numbers','**Solution**\r\nFirst, substitute the given values of $ z_1 $ and $ z_2 $:\r\n\r\n$$\r\n3z_1 - 2z_2 = 3(-3 + 4i) - 2(6 - 2i)\r\n$$\r\n\r\nExpand each term:\r\n$$\r\n= (-9 + 12i) - (12 - 4i)\r\n$$\r\n\r\nSimplify:\r\n$$\r\n= -9 + 12i - 12 + 4i\r\n$$\r\n\r\nCombine like terms:\r\n$$\r\n= (-9 - 12) + (12i + 4i)\r\n$$\r\n\r\n$$\r\n= -21 + 16i\r\n$$\r\n\r\nTherefore,\r\n$$\r\n3z_1 - 2z_2 = -21 + 16i\r\n$$',NULL,'',''),
	(50,'**Question**\r\nIf $ z_1 = 4 + 2i $ and $ z_2 = 3 - 5i $, evaluate $ z_1 \\times z_2 $.','','',4,7,'Multiplying Complex Numbers','**Solution**\r\nWe have\r\n$$\r\nz_1 \\times z_2 = (4 + 2i)(3 - 5i).\r\n$$\r\n\r\nExpanding:\r\n$$\r\n= 4(3 - 5i) + 2i(3 - 5i)\r\n= 12 - 20i + 6i - 10i^2.\r\n$$\r\n\r\nSince $ i^2 = -1 $,\r\n$$\r\n= 12 - 14i - 10(-1)\r\n= 12 - 14i + 10\r\n= 22 - 14i.\r\n$$\r\n\r\nTherefore,\r\n$$\r\nz_1 \\times z_2 = 22 - 14i.\r\n$$',NULL,'',''),
	(51,'**Question**\r\nIf $ z = 5 - 3i $, evaluate $ i \\times z $.','','',4,8,'Multiplying Complex Numbers','**Solution**\r\nWe have\r\n$$\r\ni \\times z = i(5 - 3i).\r\n$$\r\n\r\nExpanding:\r\n$$\r\n= 5i - 3i^2.\r\n$$\r\n\r\nSince $ i^2 = -1 $,\r\n$$\r\n= 5i - 3(-1)\r\n= 5i + 3\r\n= 3 + 5i.\r\n$$\r\n\r\nTherefore,\r\n$$\r\ni \\times z = 3 + 5i.\r\n$$',NULL,'',''),
	(52,'**Question**\r\nIf $ z = 2 + 5i $, find $ z^2 $.','','',4,9,'Multiplying Complex Numbers','**Solution**\r\nWe have\r\n$$\r\nz^2 = (2 + 5i)^2.\r\n$$\r\n\r\nExpanding:\r\n$$\r\n= 2^2 + 2(2)(5i) + (5i)^2\r\n= 4 + 20i + 25i^2.\r\n$$\r\n\r\nSince $ i^2 = -1 $,\r\n$$\r\n= 4 + 20i - 25\r\n= -21 + 20i.\r\n$$\r\n\r\nTherefore,\r\n$$\r\nz^2 = -21 + 20i.\r\n$$',NULL,'',''),
	(53,'**Question**\r\nIf $ z = 6 + 5i $, find $ \\bar{z} $.','','',4,10,'Conjugate of a Complex Number','**Solution**\r\nThe complex conjugate of $ z = a + bi $ is $ \\bar{z} = a - bi $.\r\n\r\nTherefore, for $ z = 6 + 5i $,\r\n$$\r\n\\bar{z} = 6 - 5i.\r\n$$',NULL,'',''),
	(54,'**Question**\r\nIf $ z = 2 - 3i $, find $ \\bar{z} $.','','',4,11,'Conjugate of a Complex Number','**Solution**\r\nThe complex conjugate of $ z = a + bi $ is $ \\bar{z} = a - bi $.\r\n\r\nTherefore, for $ z = 2 - 3i $,\r\n$$\r\n\\bar{z} = 2 + 3i.\r\n$$',NULL,'',''),
	(55,'**Question**\r\nIf $ z_1 = 4 + 5i $, $ z_2 = 1 + 3i $ and $ z_3 = z_1 \\times z_2 $, find $ \\bar{z_3} $.','','',4,12,'Conjugate of a Complex Number','**Solution**\r\nFirst, find $ z_3 $:\r\n$$\r\nz_3 = (4 + 5i)(1 + 3i).\r\n$$\r\n\r\nExpanding:\r\n$$\r\n= 4(1 + 3i) + 5i(1 + 3i)\r\n= 4 + 12i + 5i + 15i^2.\r\n$$\r\n\r\nSince $ i^2 = -1 $,\r\n$$\r\n= 4 + 17i - 15\r\n= -11 + 17i.\r\n$$\r\n\r\nNow find the conjugate:\r\n$$\r\n\\bar{z_3} = -11 - 17i.\r\n$$\r\n\r\nTherefore,\r\n$$\r\n\\bar{z_3} = -11 - 17i.\r\n$$',NULL,'','');

/*!40000 ALTER TABLE `interactive_lessons_question` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
