# Generated by Django 4.2.3 on 2024-04-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_orders', '0003_alter_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
