# Generated by Django 4.2.3 on 2024-05-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_scoschool_sco_role_num'),
        ('schools_orders', '0005_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='schools.scoschool'),
        ),
    ]
