# Generated by Django 5.2.2 on 2025-07-25 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_couponredemption'),
        ('schools_orders', '0006_order_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Coupon used for this school order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_orders', to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total discount applied via coupon.', max_digits=6),
        ),
    ]
