# Generated by Django 5.2.2 on 2025-10-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools_orders', '0008_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'School Order', 'verbose_name_plural': 'School Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='boipa_reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
