# Generated by Django 4.2.3 on 2023-08-23 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swims_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swims_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': "Today's Orders",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('swims_orders.order',),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['booking'], name='swims_order_booking_d32c2a_idx'),
        ),
    ]
