# Generated by Django 4.2.3 on 2024-01-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swims_orders', '0004_remove_orderitem_price_alter_orderitem_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNext7DaysProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Order in Next 7 Days',
                'verbose_name_plural': 'Orders in Next 7 Days',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('swims_orders.order',),
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Swim Order', 'verbose_name_plural': 'Swim Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Swim Orderitem', 'verbose_name_plural': 'Swim Orderitems'},
        ),
        migrations.AlterModelOptions(
            name='orderproxy',
            options={'verbose_name_plural': "Today's Swim Orders"},
        ),
    ]
