# Generated by Django 4.2.3 on 2024-04-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swims_orders', '0005_ordernext7daysproxy_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_id',
        ),
    ]
