# Generated by Django 4.2.3 on 2024-04-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swims_orders', '0006_remove_order_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
