# Generated by Django 4.2.3 on 2024-04-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swims_orders', '0007_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
