# Generated by Django 4.2.3 on 2024-04-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swims_orders', '0008_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='txId',
        ),
    ]
