# Generated by Django 5.2.2 on 2025-07-24 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_couponredemption'),
        ('swims_orders', '0012_order_coupon_order_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Coupon used for this swim order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swim_orders', to='coupons.coupon'),
        ),
    ]
