# Generated by Django 5.2.2 on 2025-10-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swims_orders', '0013_alter_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='boipa_reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
