# Generated by Django 5.2.2 on 2025-10-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swims_orders', '0014_order_boipa_reconciled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
