# Generated by Django 5.2.2 on 2025-08-13 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0006_category_short_name'),
        ('lessons_bookings', '0008_alter_lessonenrollment_swimling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rolls', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rolls', to='lessons.product')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_rolls', to='lessons_bookings.term')),
            ],
            options={
                'ordering': ['-window_start'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swimling_id', models.IntegerField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('unknown', 'Not Marked')], default='unknown', max_length=16)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_entries', to='lessons_bookings.lessonenrollment')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marks', to=settings.AUTH_USER_MODEL)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='anseo.attendanceroll')),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendanceroll',
            constraint=models.UniqueConstraint(fields=('product', 'term', 'window_start'), name='uniq_roll_per_product_term_per_8h_window'),
        ),
        migrations.AddIndex(
            model_name='attendanceentry',
            index=models.Index(fields=['roll', 'enrolment'], name='anseo_atten_roll_id_18a3e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceentry',
            unique_together={('roll', 'enrolment')},
        ),
    ]
