# Generated by Django 5.2.2 on 2025-08-14 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anseo', '0001_initial'),
        ('lessons_bookings', '0008_alter_lessonenrollment_swimling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendanceentry',
            name='anseo_atten_roll_id_18a3e9_idx',
        ),
        migrations.RenameField(
            model_name='attendanceentry',
            old_name='enrolment',
            new_name='enrollment',
        ),
        migrations.AlterUniqueTogether(
            name='attendanceentry',
            unique_together={('roll', 'enrollment')},
        ),
        migrations.AddIndex(
            model_name='attendanceentry',
            index=models.Index(fields=['roll', 'enrollment'], name='anseo_atten_roll_id_03d9d2_idx'),
        ),
    ]
