# Generated by Django 5.2.2 on 2025-07-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_faqentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqentry',
            name='lessons_only',
            field=models.BooleanField(default=False, help_text='Check this if this FAQ is *only* for the lessons chatbot.'),
        ),
    ]
