# Generated by Django 5.2.2 on 2025-07-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_faqentry_lessons_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotquery',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Embedding match confidence (0.0–1.0)', null=True),
        ),
    ]
