# Generated by Django 5.2.2 on 2025-07-31 11:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatbotquery_confidence_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqentry',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
