# Generated by Django 5.2.2 on 2025-11-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_faqentry_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotquery',
            name='response',
            field=models.TextField(blank=True, help_text="Bot's response to the query"),
        ),
    ]
