# Generated by Django 5.2.2 on 2025-07-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_created_at_coupon_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='balance_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
