# Generated by Django 5.2.2 on 2025-07-16 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_balance_remaining_alter_coupon_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Optionally restrict this coupon to a specific user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_specific_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
