# Generated by Django 5.2.2 on 2025-10-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_couponredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='note',
            field=models.TextField(blank=True, help_text='Optional notes about this coupon.', null=True),
        ),
    ]
