# Generated by Django 5.2.2 on 2025-10-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_coupon_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='note',
            field=models.CharField(blank=True, help_text='Optional note', max_length=255, null=True),
        ),
    ]
