# Generated by Django 5.2.2 on 2025-11-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_alter_coupon_note'),
        ('lessons', '0008_alter_category_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='limited_to_products',
            field=models.ManyToManyField(blank=True, help_text='If selected, this coupon can only be used for these specific products. Leave blank to allow all products.', related_name='limited_coupons', to='lessons.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used. Leave blank for unlimited uses (balance permitting).', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='multi_use',
            field=models.BooleanField(default=False, help_text='If enabled, this coupon can be used multiple times (balance permitting). If disabled, coupon is single-use only.'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='times_used',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used.'),
        ),
    ]
