# Generated by Django 5.2.2 on 2025-11-03 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_coupon_limited_to_products_coupon_max_uses_and_more'),
        ('lessons', '0008_alter_category_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='limited_to_categories',
            field=models.ManyToManyField(blank=True, help_text='If selected, this coupon can only be used for products in these categories. Leave blank to allow all categories.', related_name='limited_coupons', to='lessons.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limited_to_programs',
            field=models.ManyToManyField(blank=True, help_text='If selected, this coupon can only be used for products in these programs. Leave blank to allow all programs.', related_name='limited_coupons', to='lessons.program'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order value required to use this coupon. Leave blank for no minimum.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_context',
            field=models.CharField(choices=[('any', 'Any (Lessons, Schools, Admin)'), ('lessons', 'Lessons Only'), ('schools', 'Schools Only'), ('admin', 'Admin Use Only')], default='any', help_text='Restrict where this coupon can be used.', max_length=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_by_users',
            field=models.ManyToManyField(blank=True, help_text='Tracks which users have used this coupon.', related_name='used_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
