# Generated by Django 5.2.2 on 2025-11-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0009_coupon_limited_to_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='usage_context',
            field=models.CharField(choices=[('any', 'Any (Lessons, Schools, Swims, Admin)'), ('lessons', 'Lessons Only'), ('schools', 'Schools Only'), ('swims', 'Public Swims Only'), ('admin', 'Admin Use Only')], default='any', help_text='Restrict where this coupon can be used.', max_length=10),
        ),
    ]
