# Generated by Django 5.2.17 on 2026-10-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0010_add_swims_usage_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponredemption',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
