# Generated by Django 4.2.3 on 2023-08-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicswimproduct',
            options={'ordering': ['day_of_week'], 'verbose_name': 'Public Swims', 'verbose_name_plural': 'Public Swims'},
        ),
        migrations.AlterField(
            model_name='publicswimcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
