# Generated by Django 4.2.3 on 2023-12-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swims', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricevariant',
            unique_together={('product', 'variant')},
        ),
    ]
