# Generated by Django 4.2.3 on 2023-12-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swims', '0002_alter_pricevariant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricevariant',
            name='variant',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Child', 'Child'), ('OAP', 'OAP'), ('Student', 'Student'), ('Infant', 'Infant')], max_length=10),
        ),
    ]
