# Generated by Django 4.2.3 on 2023-08-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swims', '0002_alter_publicswimproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicswimcategory',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publicswimproduct',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
