# Generated by Django 4.2.3 on 2023-08-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swims', '0003_alter_publicswimcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicswimproduct',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
