# Generated by Django 4.2.3 on 2025-06-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swims', '0003_alter_pricevariant_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicswimproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
