# Generated by Django 4.2.3 on 2025-06-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swims', '0004_alter_publicswimproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicswimproduct',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
