# Generated by Django 4.2.3 on 2024-04-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swims_orders', '0005_ordernext7daysproxy_alter_order_options_and_more'),
        ('boipa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentnotification',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='swims_orders.order'),
            preserve_default=False,
        ),
    ]
