# Generated by Django 4.2.3 on 2024-04-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swims_orders', '0010_order_amount'),
        ('lessons_orders', '0003_rename_stripe_id_order_txid_order_amount_and_more'),
        ('boipa', '0002_paymentnotification_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentNotification',
            new_name='LessonOrderPaymentNotification',
        ),
        migrations.AlterField(
            model_name='lessonorderpaymentnotification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='lessons_orders.order'),
        ),
        migrations.CreateModel(
            name='SwimOrderPaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txId', models.CharField(max_length=50)),
                ('merchantTxId', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('action', models.CharField(blank=True, max_length=10, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=10, null=True)),
                ('acquirer', models.CharField(blank=True, max_length=100, null=True)),
                ('acquirerAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('merchantId', models.CharField(blank=True, max_length=50, null=True)),
                ('brandId', models.CharField(blank=True, max_length=50, null=True)),
                ('customerId', models.CharField(max_length=50, null=True)),
                ('acquirerCurrency', models.CharField(blank=True, max_length=3, null=True)),
                ('paymentSolutionId', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='swims_orders.order')),
            ],
        ),
    ]
