# Generated by Django 4.2.3 on 2024-05-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boipa', '0004_schoolorderpaymentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonorderpaymentnotification',
            name='errorMessage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolorderpaymentnotification',
            name='errorMessage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swimorderpaymentnotification',
            name='errorMessage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
