# Generated by Django 5.2.2 on 2025-10-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boipa', '0006_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonorderpaymentnotification',
            name='auth_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolorderpaymentnotification',
            name='auth_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='swimorderpaymentnotification',
            name='auth_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
