# Generated by Django 5.2.2 on 2025-10-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boipa', '0007_alter_lessonorderpaymentnotification_auth_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonorderpaymentnotification',
            name='acquirer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lessonorderpaymentnotification',
            name='action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lessonorderpaymentnotification',
            name='brandId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lessonorderpaymentnotification',
            name='customerId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lessonorderpaymentnotification',
            name='merchantId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lessonorderpaymentnotification',
            name='merchantTxId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonorderpaymentnotification',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lessonorderpaymentnotification',
            name='txId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolorderpaymentnotification',
            name='acquirer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolorderpaymentnotification',
            name='action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schoolorderpaymentnotification',
            name='brandId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schoolorderpaymentnotification',
            name='customerId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolorderpaymentnotification',
            name='merchantId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schoolorderpaymentnotification',
            name='merchantTxId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolorderpaymentnotification',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schoolorderpaymentnotification',
            name='txId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='swimorderpaymentnotification',
            name='acquirer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='swimorderpaymentnotification',
            name='action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='swimorderpaymentnotification',
            name='brandId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='swimorderpaymentnotification',
            name='customerId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='swimorderpaymentnotification',
            name='merchantId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='swimorderpaymentnotification',
            name='merchantTxId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='swimorderpaymentnotification',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='swimorderpaymentnotification',
            name='txId',
            field=models.CharField(max_length=100),
        ),
    ]
