# Generated by Django 4.2.3 on 2023-08-23 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons_bookings', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonenrollment',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonenrollment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.product'),
        ),
        migrations.AddField(
            model_name='lessonenrollment',
            name='swimling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.swimling'),
        ),
        migrations.AddField(
            model_name='lessonenrollment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons_bookings.term'),
        ),
        migrations.AddField(
            model_name='lessonassignment',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'instructors'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonassignment',
            name='lessons',
            field=models.ManyToManyField(to='lessons.product'),
        ),
        migrations.AddField(
            model_name='lessonassignment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons_bookings.term'),
        ),
        migrations.AddIndex(
            model_name='lessonenrollment',
            index=models.Index(fields=['term', 'lesson', 'swimling'], name='lessons_boo_term_id_f78011_idx'),
        ),
    ]
