# Generated by Django 4.2.3 on 2023-08-13 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('users', '0009_alter_swimling_wp_student_id'),
        ('lessons_orders', '0003_orderitem_swimling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons_bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instructor1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor1', to=settings.AUTH_USER_MODEL)),
                ('instructor2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor2', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons_orders.order')),
                ('swimling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.swimling')),
            ],
            options={
                'ordering': ['-term', 'lesson'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.IntegerField(unique=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('rebooking', models.DateField()),
                ('booking', models.DateField()),
                ('assessments', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Terms',
        ),
        migrations.AddField(
            model_name='lessonenrollment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons_bookings.term'),
        ),
        migrations.AddIndex(
            model_name='lessonenrollment',
            index=models.Index(fields=['term', 'lesson', 'swimling'], name='lessons_boo_term_id_f78011_idx'),
        ),
    ]
