# Generated by Django 4.2.3 on 2023-08-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_bookings', '0002_lessonenrollment_term_delete_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonenrollment',
            name='order',
        ),
    ]
