# Generated by Django 4.2.3 on 2023-08-13 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0001_initial'),
        ('lessons_bookings', '0003_remove_lessonenrollment_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(limit_choices_to={'groups__name': 'instructors'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('lessons', models.ManyToManyField(to='lessons.product')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons_bookings.term')),
            ],
        ),
    ]
