# Generated by Django 4.2.3 on 2024-01-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_bookings', '0003_lessonenrollment_notes_lessonenrollment_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonassignment',
            options={'verbose_name': 'Instructor Assignment', 'verbose_name_plural': 'Instructor Assignments'},
        ),
    ]
