# Generated by Django 4.2.3 on 2023-08-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_bookings', '0004_lessonassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonenrollment',
            name='instructor1',
        ),
        migrations.RemoveField(
            model_name='lessonenrollment',
            name='instructor2',
        ),
    ]
