# Generated by Django 4.2.3 on 2024-05-18 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_delete_area'),
        ('lessons_bookings', '0004_alter_lessonassignment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonenrollment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lessons.product'),
        ),
    ]
