# Generated by Django 5.2.2 on 2025-06-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_product_end_time_alter_product_start_time'),
        ('lessons_bookings', '0006_alter_term_assessment_date_alter_term_booking_date_and_more'),
        ('users', '0013_alter_swimling_sco_role_num'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonenrollment',
            unique_together={('swimling', 'lesson', 'term')},
        ),
    ]
