# Generated by Django 5.2.2 on 2025-07-15 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_bookings', '0007_alter_lessonenrollment_unique_together'),
        ('users', '0014_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonenrollment',
            name='swimling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.swimling'),
        ),
    ]
