# Generated by Django 5.2.2 on 2025-10-03 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_bookings', '0008_alter_lessonenrollment_swimling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-start_date', '-id']},
        ),
        migrations.AlterField(
            model_name='lessonassignment',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'groups__name__in': ['instructor', 'Instructor', 'instructors', 'Instructors']}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
