# Generated by Django 5.2.2 on 2026-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_bookings', '0009_alter_term_options_alter_lessonassignment_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='pause_date',
            field=models.DateField(blank=True, help_text='Optional. From this day until the booking date, public lesson booking is paused so classes can be reshuffled. Staff can still book swimlings in. Leave blank to run rebooking straight through to the booking date.', null=True),
        ),
    ]
