# Generated by Django 5.2.2 on 2026-08-20 12:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField(blank=True, help_text='Optional. One or two sentences.')),
                ('link_url', models.URLField(blank=True, help_text='Optional. Where the button goes.')),
                ('link_text', models.CharField(blank=True, help_text="Button label, e.g. 'Book now'.", max_length=60)),
                ('is_active', models.BooleanField(default=False, help_text='Tick to show on the home page.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home page notice',
                'ordering': ['-updated'],
            },
        ),
    ]
