# Generated by Django 5.2.2 on 2026-08-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_on',
            field=models.DateField(blank=True, help_text="Optional. Last day the notice is shown — it disappears by itself the morning after. Leave blank to show until you untick 'Is active'.", null=True),
        ),
    ]
