# Generated by Django 5.2.2 on 2025-07-14 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0005_alter_product_end_time_alter_product_start_time'),
        ('lessons_bookings', '0007_alter_lessonenrollment_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_level', models.CharField(choices=[('Level 1', 'Assistant Swimming Teacher'), ('Level 2', 'Swimming Teacher')], max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(limit_choices_to={'groups__name': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.product')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons_bookings.term')),
            ],
            options={
                'unique_together': {('lesson', 'term')},
            },
        ),
    ]
