"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv

load_dotenv()  # loads the configs from .env
DB_PASSWORD = str(os.getenv('DB_PASSWORD')),

# Set the URL prefix for static files
STATIC_URL = '/static/'

# Specify the directory where static files are collected
STATIC_ROOT = os.path.join(BASE_DIR, 'static_files/')

# Specify additional directories to search for static files
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'

# Specify the directory where uploaded media files are stored
MEDIA_ROOT = os.path.join(BASE_DIR, '../media')



SECRET_KEY = str(os.getenv('SECRET_KEY'))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Allauth
    # Installed Apps
    'allauth',  # Allauth
    'allauth.account',  # Allauth
    'allauth.socialaccount',  # Allauth
    'allauth.socialaccount.providers.google',  # Allauth
    'allauth.socialaccount.providers.facebook',  # Allauth
    "bootstrap5",
    'django_bootstrap_icons',
    "crispy_forms",
    "crispy_bootstrap5",
    # My Apps
    'users',
    'home',
    'lessons',
    'lessons_cart',
    'lessons_orders',
    'lessons_payment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                # `allauth` needs this from django
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


# Define the directory where Django should collect and store static files
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')




# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Allauth
SITE_ID = 2
LOGIN_REDIRECT_URL = '/'

# ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_UNIQUE = True
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300
SOCIALACCOUNT_AUTO_SIGNUP = False
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
ACCOUNT_SIGNUP_REQUIRED_FIELDS = ['first_name']
# disable sign out confirmation
ACCOUNT_LOGOUT_ON_GET = True
# # disable sign in confirmation
SOCIALACCOUNT_LOGIN_ON_GET = True
# # ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
# #
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_AUTHENTICATION_METHOD = 'email'
# Will remember you
# ACCOUNT_SESSION_REMEMBER = True

#  Allauth social accounts
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }, 'facebook': {
        'METHOD': 'oauth2',
        # 'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        # 'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
        'GRAPH_API_URL': 'https://graph.facebook.com/v13.0',
    }
}
ACCOUNT_FORMS = {
    'signup': 'users.forms.CustomSignupForm',
}
# CrispyForms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

# ***  E-Commerce

# How cart sessions are stored
CART_SESSION_ID = 'cart'

# STRIPE_PUBLISHABLE_KEY = 'pk_test_51NVtpDEFFHpYE55Q12mZc5DlWSTFoA0mRceNzaU1uFM4yN2I7mPiDEpOvjxCCTfd9ZjbR6dgmSL1zlxxOKFgDzMH00QiVhAbQD'
# STRIPE_SECRET_KEY = 'sk_test_51NVtpDEFFHpYE55QcBDG03wvvJzYo1gWoPkTlbdMKVeVhiCBcDhpANTArmJrjZONezVXM1CCvOubQTwQpGHtGnNK00W4qZXuFk'


# This is your Stripe CLI webhook secret for testing your endpoint locally.
# STRIPE_WEBHOOK_SECRET = \
#     'whsec_8451c76fcd43e9f51a8480ca699b2a65ff7aebb84bb31997e3346e3478750b27'
STRIPE_PUBLISHABLE_KEY = str(os.getenv('STRIPE_PUBLISHABLE_KEY'))
STRIPE_SECRET_KEY = str(os.getenv('STRIPE_SECRET_KEY'))
STRIPE_WEBHOOK_SECRET = str(os.getenv('STRIPE_WEBHOOK_SECRET'))
STRIPE_API_VERSION = '2022-08-01'
