# Generated by Django 5.2.2 on 2025-07-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetableoverride_delete_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimetableOverride',
        ),
    ]
