# Generated by Django 5.2.2 on 2025-07-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0003_delete_timetableoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('term', 'Term Dates'), ('rebooking', 'Rebooking Window'), ('closure', 'Closure'), ('special', 'Special Event')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
