# Generated by Django 4.2.3 on 2024-02-15 08:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'School category',
                'verbose_name_plural': 'School categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sco_name', models.CharField(blank=True, default='', max_length=50)),
                ('roll_num', models.CharField(blank=True, default='', max_length=7)),
                ('add1', models.CharField(blank=True, default='', max_length=50)),
                ('add2', models.CharField(blank=True, default='', max_length=50)),
                ('add3', models.CharField(blank=True, default='', max_length=50)),
                ('eircode', models.CharField(blank=True, default='', max_length=7)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('start_time', models.TimeField(blank=True, default=datetime.time(8, 0))),
                ('end_time', models.TimeField(blank=True, default=datetime.time(9, 0))),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('num_places', models.IntegerField(null=True)),
                ('num_weeks', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='images/default_image.jpg', upload_to='products/%Y/%m/%d')),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.scoarea')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.scocategory')),
            ],
            options={
                'verbose_name': 'School Lessons',
                'verbose_name_plural': 'School Lessons',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.AddField(
            model_name='scocategory',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='schools.scoprogram'),
        ),
        migrations.AddIndex(
            model_name='scocategory',
            index=models.Index(fields=['name'], name='schools_sco_name_98abfb_idx'),
        ),
    ]
