# Generated by Django 4.2.3 on 2024-02-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_scocategory_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scolessons',
            name='area',
        ),
        migrations.AddField(
            model_name='scolessons',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_lessons', to='schools.scoschool'),
        ),
    ]
