# Generated by Django 4.2.3 on 2024-02-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_scolessons_area_scolessons_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoArea',
        ),
    ]
