# Generated by Django 4.2.3 on 2024-05-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_rename_sco_name_scoschool_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoschool',
            old_name='roll_num',
            new_name='sco_role_num',
        ),
    ]
