# Generated by Django 4.2.3 on 2024-05-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_rename_roll_num_scoschool_sco_role_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoschool',
            name='sco_role_num',
            field=models.CharField(blank=True, default='', max_length=7, unique=True),
        ),
    ]
