# Generated by Django 4.2.3 on 2023-08-23 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons_orders', '0001_initial'),
        ('lessons_bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='swimling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimling', to='users.swimling'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons_bookings.term'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created'], name='lessons_ord_created_4daa6e_idx'),
        ),
    ]
