# Generated by Django 4.2.3 on 2023-08-12 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_swimling_wp_student_id'),
        ('lessons_orders', '0002_order_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='swimling',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='swimling', to='users.swimling'),
            preserve_default=False,
        ),
    ]
