# Generated by Django 5.2.2 on 2025-07-24 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_couponredemption'),
        ('lessons_orders', '0007_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Coupon used for this lesson order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_orders', to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total discount applied from the coupon.', max_digits=6, null=True),
        ),
    ]
