# Generated by Django 5.2.2 on 2025-10-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_orders', '0008_order_coupon_order_discount_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Lesson Order', 'verbose_name_plural': 'Lesson Orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='boipa_reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
