# Generated by Django 5.2.2 on 2025-06-16 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url_name', models.CharField(blank=True, help_text='Name of a Django URL pattern', max_length=100)),
                ('external_url', models.URLField(blank=True, help_text='Used only if url_name is not set')),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome or custom icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('requires_login', models.BooleanField(default=False)),
                ('requires_staff', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navigation.menugroup')),
                ('required_groups', models.ManyToManyField(blank=True, to='auth.group')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
