# Generated by Django 5.2.2 on 2025-06-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menugroup',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='menugroup',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
