# Generated by Django 5.2.2 on 2025-06-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_alter_menugroup_options_menugroup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='external_url',
            field=models.CharField(blank=True, help_text='Used only if url_name is not set. Accepts relative or absolute URLs.', max_length=200),
        ),
    ]
