# Generated by Django 5.2.2 on 2025-07-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_alter_menuitem_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this menu item.'),
        ),
    ]
