# Generated by Django 5.2.2 on 2025-07-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('navigation', '0004_menuitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='excluded_groups',
            field=models.ManyToManyField(blank=True, help_text='Users in these groups will NOT see this menu item.', related_name='excluded_from_menuitems', to='auth.group'),
        ),
    ]
