# Generated by Django 4.2.3 on 2024-02-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_rename_group_area_rename_group_product_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='area',
        ),
    ]
