# Generated by Django 4.2.3 on 2024-02-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_product_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
