# Generated by Django 4.2.3 on 2025-06-07 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_delete_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
    ]
