# Generated by Django 5.2.2 on 2025-08-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_category_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='stage',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Stage 1', 'Stage 1'), ('Stage 2', 'Stage 2'), ('Stage 3', 'Stage 3'), ('Stage 4', 'Stage 4'), ('Stage 5', 'Stage 5'), ('Stage 6', 'Stage 6'), ('Stage 7', 'Stage 7'), ('Stage 8', 'Stage 8')], help_text='Optional stage mapping for this category (Stage 1–8)', max_length=20),
        ),
    ]
