# Generated by Django 5.2.2 on 2025-08-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_category_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='stage',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Stage 1', 'Stage 1'), ('Stage 2', 'Stage 2'), ('Stage 3', 'Stage 3'), ('Stage 4', 'Stage 4'), ('Stage 5', 'Stage 5'), ('Stage 6', 'Stage 6'), ('Stage 7', 'Stage 7'), ('Stage 8', 'Stage 8'), ('Stage 9', 'Stage 9'), ('Stage 10', 'Stage 10')], help_text='Optional stage mapping for this category (Stage 1–8)', max_length=20),
        ),
    ]
