# Generated by Django 5.2.2 on 2025-11-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_category_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weekly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per lesson (weekly). Full term price is calculated as weekly_price × num_weeks.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy full term price. Use weekly_price instead for new products.', max_digits=10, null=True),
        ),
    ]
