# Generated by Django 5.2.2 on 2025-12-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0009_add_weekly_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Full term price (auto-calculated as weekly_price × num_weeks). Leave blank - will be set automatically.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
