# Generated by Django 4.2.3 on 2024-05-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitinglist',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
