# Generated by Django 4.2.3 on 2024-05-19 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_delete_area'),
        ('waiting_list', '0002_rename_date_joined_waitinglist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='assigned_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lessons', to='lessons.product'),
        ),
    ]
