# Generated by Django 4.2.3 on 2024-05-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_swimling_sco_role_num'),
        ('lessons', '0004_delete_area'),
        ('waiting_list', '0004_waitinglist_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waitinglist',
            unique_together={('swimling', 'product')},
        ),
    ]
