# Generated by Django 5.2.2 on 2025-07-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0005_alter_waitinglist_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='user',
        ),
    ]
