# Generated by Django 5.2.2 on 2025-07-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0006_remove_waitinglist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
