# Generated by Django 5.2.2 on 2025-08-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_product_end_time_alter_product_start_time'),
        ('waiting_list', '0007_waitinglist_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='has_sibling_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='is_transfer_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='preferred_lesson_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_1', to='lessons.product'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='preferred_lesson_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_2', to='lessons.product'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='preferred_lesson_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_3', to='lessons.product'),
        ),
    ]
