# Generated by Django 5.2.2 on 2025-08-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0008_waitinglist_has_sibling_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
